services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    privileged: true # Enable privileged mode for DinD
    environment:
      DOCKER_HOST: "tcp://docker:2375" # Point to the DinD service
    depends_on:
      - docker
    networks:
      - dind-network

  docker:
    image: docker:latest
    privileged: true
    command: ["dockerd", "--host=tcp://0.0.0.0:2375"]
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - dind-network

networks:
  dind-network:
    driver: bridge
